/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedClientesRouteImport } from './routes/_authenticated/clientes'
import { Route as AuthenticatedNovaRouteImport } from './routes/_authenticated/nova'
import { Route as AuthenticatedProdutosRouteImport } from './routes/_authenticated/produtos'
import { Route as PropostaCodeRouteImport } from './routes/proposta.$code'

const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/_authenticated/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedClientesRoute = AuthenticatedClientesRouteImport.update({
  id: '/_authenticated/clientes',
  path: '/clientes',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedNovaRoute = AuthenticatedNovaRouteImport.update({
  id: '/_authenticated/nova',
  path: '/nova',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProdutosRoute = AuthenticatedProdutosRouteImport.update({
  id: '/_authenticated/produtos',
  path: '/produtos',
  getParentRoute: () => rootRouteImport,
} as any)
const PropostaCodeRoute = PropostaCodeRouteImport.update({
  id: '/proposta/$code',
  path: '/proposta/$code',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/clientes': typeof AuthenticatedClientesRoute
  '/nova': typeof AuthenticatedNovaRoute
  '/produtos': typeof AuthenticatedProdutosRoute
  '/proposta/$code': typeof PropostaCodeRoute
  '/': typeof AuthenticatedIndexRoute
}
export interface FileRoutesByTo {
  '/clientes': typeof AuthenticatedClientesRoute
  '/nova': typeof AuthenticatedNovaRoute
  '/produtos': typeof AuthenticatedProdutosRoute
  '/proposta/$code': typeof PropostaCodeRoute
  '/': typeof AuthenticatedIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated/clientes': typeof AuthenticatedClientesRoute
  '/_authenticated/nova': typeof AuthenticatedNovaRoute
  '/_authenticated/produtos': typeof AuthenticatedProdutosRoute
  '/proposta/$code': typeof PropostaCodeRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/clientes' | '/nova' | '/produtos' | '/proposta/$code' | '/'
  fileRoutesByTo: FileRoutesByTo
  to: '/clientes' | '/nova' | '/produtos' | '/proposta/$code' | '/'
  id:
    | '__root__'
    | '/_authenticated/clientes'
    | '/_authenticated/nova'
    | '/_authenticated/produtos'
    | '/proposta/$code'
    | '/_authenticated/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedClientesRoute: typeof AuthenticatedClientesRoute
  AuthenticatedNovaRoute: typeof AuthenticatedNovaRoute
  AuthenticatedProdutosRoute: typeof AuthenticatedProdutosRoute
  PropostaCodeRoute: typeof PropostaCodeRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/clientes': {
      id: '/_authenticated/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof AuthenticatedClientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/nova': {
      id: '/_authenticated/nova'
      path: '/nova'
      fullPath: '/nova'
      preLoaderRoute: typeof AuthenticatedNovaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/produtos': {
      id: '/_authenticated/produtos'
      path: '/produtos'
      fullPath: '/produtos'
      preLoaderRoute: typeof AuthenticatedProdutosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proposta/$code': {
      id: '/proposta/$code'
      path: '/proposta/$code'
      fullPath: '/proposta/$code'
      preLoaderRoute: typeof PropostaCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedClientesRoute: AuthenticatedClientesRoute,
  AuthenticatedNovaRoute: AuthenticatedNovaRoute,
  AuthenticatedProdutosRoute: AuthenticatedProdutosRoute,
  PropostaCodeRoute: PropostaCodeRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
